services:
  db:
    image: postgres:latest
    container_name: tres-comas-db
    environment:
      POSTGRES_DB: tres-comas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
        
  iris-fhir:
    image: skalahonza/fajr
    container_name: iris-fhir
    restart: unless-stopped
    ports:
      - "8080:52773"  # Map local port 8080 to IRIS web port 52773
    #    volumes:
    #      - ./data:/data  # Map local 'data' directory to '/data' inside container
    environment:
      ISC_DATA_DIRECTORY: /data/ifconfig
      ISC_CPF_MERGE_FILE: /merge/CMF.cpf
    entrypoint: ["/iris-main"]